all: main.cpp board.cpp board_unittest.cpp 
	g++ -std=c++11 main.cpp board.cpp board_unittest.cpp -I ./googletest/googletest/include -L ./googletest/install/lib -lgtest -lgtest_main -pthread -o gameoflife

