#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

create:
  # create make
  cmake -S . -B ./build

build:
  # build target
  cmake --build ./build

run:
  # run 
  ./build/helloworld

clean:
  # cleanup
  cmake --build ./build --target clean


